### PR TITLE
Lesson1.2–react fundamentals react dom and components

### PR DESCRIPTION
**Pull request by Said-laasri**
**Create:**

1. TodoList component 
```
Add to TodoList 
todolist array 
```
3. AddTodoForm component
```
add to AddTodoForm 
form to add todos 
```

### CODE REVIEW

**Review by mogulafric — COMMENTED** [review]
Component well created!

**Review by mogulafric — COMMENTED** [review]
todoList and addTodoForm components correctly imported.

**Review by leo-mutuku — COMMENTED** [review]
Form styled correctly

**Review by leo-mutuku — COMMENTED** [review]
Changes well effected. Changed index to id.
Perfect.

**Comment by leo-mutuku** [comment]
Lesson 1.2 completed. Met all the objectives

**Pull request merged**
